import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, ExternalLink, FileCheck2, ListChecks, TimerReset } from "lucide-react";
import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import { createPageMetadata } from "@/lib/seo";

export const metadata: Metadata = createPageMetadata({ title: "GCSE Exam Resources 2027: Timetables, Command Words & Checklists", description: "Prepare for 2027 GCSE exams with official timetable links, command-word guidance, required-practical checklists and a realistic revision routine.", path: "/exam-resources" });

const commandWords = [
  ["Calculate", "Show the equation or method, substitute carefully, include units and round only at the end."],
  ["Compare", "Give a relevant similarity and/or difference using both items throughout the answer."],
  ["Describe", "State the pattern, feature or sequence clearly. Use data where the question provides it."],
  ["Explain", "Link a cause to its effect using clear reasoning: because, therefore, which means."],
  ["Evaluate", "Use evidence for different sides, weigh their importance and finish with a supported judgement."],
  ["Suggest", "Apply your knowledge to the unfamiliar context; the answer may not be stated directly."],
];

export default function ExamResourcesPage() {
  return <div className="min-h-screen bg-slate-50"><Navbar /><section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><span className="rounded-full bg-indigo-500/20 px-3 py-1.5 text-xs font-black text-indigo-200">2027 exam season hub</span><h1 className="mt-5 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">Everything around the content, in one calm place.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Official timetable links, exam technique, practical checklists and a repeatable past-paper routine. Check official sources again before making travel or attendance plans.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.aqa.org.uk/exams-administration/dates-and-timetables" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-5 py-3 text-sm font-bold">Official AQA dates and timetables <ExternalLink className="h-4 w-4" /></a><Link href="/past-papers" className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-5 py-3 text-sm font-bold">Open past papers <ArrowRight className="h-4 w-4" /></Link></div></div></section><main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><section className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[
    { icon: CalendarDays, title: "Confirm the dates", text: "Use your school timetable as the final authority and compare it with the official board timetable." },
    { icon: ListChecks, title: "Map the specification", text: "Mark each topic red, amber or green using quiz evidence—not confidence alone." },
    { icon: TimerReset, title: "Practise to time", text: "Complete whole papers, then isolate whether lost marks came from knowledge, method or timing." },
    { icon: FileCheck2, title: "Repair the gaps", text: "Add every wrong quiz answer to your mistake notebook and revisit it until you can explain it." },
  ].map((item) => <article key={item.title} className="rounded-2xl border border-slate-200 bg-white p-6"><item.icon className="h-6 w-6 text-indigo-600" /><h2 className="mt-4 text-lg font-black">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{item.text}</p></article>)}</section><section className="mt-12"><p className="text-xs font-black uppercase tracking-[.16em] text-indigo-600">Exam command words</p><h2 className="mt-2 text-3xl font-black">Know what the marker is asking you to do.</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{commandWords.map(([word, meaning]) => <article key={word} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black text-indigo-700">{word}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{meaning}</p></article>)}</div></section><section className="mt-12 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-7"><h2 className="text-2xl font-black text-emerald-950">Science practical checklist</h2><ul className="mt-5 space-y-3 text-sm leading-6 text-emerald-950">{["State the independent, dependent and control variables.", "Describe a repeatable method with named equipment and measurements.", "Identify a realistic hazard and matching control measure.", "Explain repeats, means, anomalies and how reliability improves.", "Choose a suitable graph and interpret its pattern in context."].map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-emerald-600" />{item}</li>)}</ul></div><div className="rounded-3xl bg-indigo-600 p-7 text-white"><h2 className="text-2xl font-black">A realistic weekly cycle</h2><ol className="mt-5 space-y-3 text-sm leading-6 text-indigo-50"><li><strong>Monday–Thursday:</strong> two focused 15-minute topic blocks.</li><li><strong>Friday:</strong> review the mistake notebook and due flashcards.</li><li><strong>Weekend:</strong> one timed paper section, strict marking, then repair one gap.</li><li><strong>Every Sunday:</strong> adjust the next week from evidence, not guilt.</li></ol><Link href="/my-revision/setup" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-indigo-700">Build my daily plan <ArrowRight className="h-4 w-4" /></Link></div></section></main><Footer /></div>;
}
